name = "polygon-token-list"
main = "src/wrangler_main.js"
compatibility_date = "2024-12-30"
placement = { mode = "smart" }
preview_urls = false
send_metrics = false
workers_dev = false

[env.staging]
routes = [
    "api-polygon-tokens.staging.polygon.technology/*"
]

[env.production]
routes = [
    "api-polygon-tokens.polygon.technology/*"
]
