name = "polygon-token-list"
main = "src/worker.js"
compatibility_date = "2024-12-30"
placement = { mode = "smart" }
preview_urls = false
send_metrics = false
workers_dev = false

# Static assets with worker for OPTIONS handling
[assets]
directory = "build"

[env.staging]
routes = [
    { pattern = "api-polygon-tokens.staging.polygon.technology", custom_domain = true },
]

[env.production]
routes = [
    { pattern = "api-polygon-tokens-cf.polygon.technology", custom_domain = true },
]