name: Portal Deployment GCP

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: "Select the environment to deploy to"
        options:
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  docker-release:
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
      (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod')
    uses: 0xPolygon/pipelines/.github/workflows/gcp_pipeline_release_image.yaml@main
    with:
      image_name: api-polygon-tokens
      environment: ${{ inputs.environment || (github.ref == 'refs/heads/dev' && 'dev') || (github.ref == 'refs/heads/master' && 'prod') }}